# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Appointments',
    'version': '1.3',
    'category': 'Services/Appointment',
    'sequence': 215,
    'summary': 'Allow people to book meetings in your agenda',
    'website': 'https://www.odoo.com/app/appointments',
    'description': """
Allow clients to Schedule Appointments through the Portal
    """,
    'depends': ['calendar', 'digest', 'phone_validation', 'portal', 'resource', 'web_gantt', 'rating'],
    'data': [
        'data/appointment_question_data.xml',
        'data/appointment_tour.xml',
        'data/digest_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_message_subtype_data.xml',
        'data/mail_template_data.xml',
        'data/resource_calendar_data.xml',
        'data/portal_entry_data.xml',
        'security/res_groups_data.xml',
        'views/calendar_alarm_views.xml',
        'views/calendar_event_views.xml',
        'views/appointment_answer_input_views.xml',
        'views/appointment_answer_views.xml',
        'views/appointment_invite_views.xml',
        'views/appointment_leave_views.xml',
        'views/appointment_question_views.xml',
        'views/appointment_rating_views.xml',
        'views/appointment_resource_views.xml',
        'views/appointment_type_views.xml',
        'views/appointment_slot_views.xml',
        'views/appointment_menus.xml',
        'views/calendar_menus.xml',
        'views/appointment_templates_appointments.xml',
        'views/appointment_templates_registration.xml',
        'views/appointment_templates_validation.xml',
        'views/digest_views.xml',
        'views/portal_templates.xml',
        'security/ir.access.csv',
    ],
    'demo': [
        'data/res_partner_demo.xml',
        'data/appointment_type_demo.xml',
        'data/appointment_resource_demo.xml',
        'data/calendar_event_demo.xml',
    ],
    'application': True,
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
    'assets': {
        'web.assets_frontend': [
            'appointment/static/src/js/utils.js',
            'appointment/static/src/scss/appointment.scss',
            'appointment/static/src/interactions/appointment_type_selection_empty_placeholder.js',
            'appointment/static/src/interactions/appointment_validation.js',
            'appointment/static/src/interactions/appointment_select_appointment_slot.js',
            'appointment/static/src/interactions/appointment_form.js',
            'appointment/static/src/xml/*.xml',
        ],
        'web.assets_backend': [
            'appointment/static/src/scss/appointment_type_views.scss',
            'appointment/static/src/scss/calendar_event_views.scss',
            'appointment/static/src/scss/web_calendar.scss',
            'appointment/static/src/views/**/*',
            ('remove', 'appointment/static/src/views/gantt/**'),
            'appointment/static/src/components/**/*',
            'appointment/static/src/fields/**/*',
            'appointment/static/src/js/appointment_insert_link_form_controller.js',
            'appointment/static/src/js/tours/appointment_tour.js',
            'appointment/static/src/appointment_plugin.js',
        ],
        "web.assets_web_dark": [
            'appointment/static/src/scss/*.dark.scss',
        ],
        'web.assets_backend_lazy': [
            'appointment/static/src/xml/*.xml',
            'appointment/static/src/views/gantt/**',
        ],
        'web.assets_unit_tests': [
            'appointment/static/tests/*',
        ],
    }
}
