# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'ESG',
    'category': 'ESG',
    'summary': "Calculate and report your company's Environmental, Social, and Governance impact.",
    'depends': [
        'account_reports',
        'base_import',
        'web_hierarchy',
        'survey',
        'accountant_knowledge',
    ],
    'data': [
        'security/esg_security.xml',
        'data/decimal_precision_data.xml',
        'data/esg_uom_data.xml',
        'data/esg_database_data.xml',
        'data/esg_emission_source_data.xml',
        'data/esg_emission_factor_data.xml',
        'data/esg_gas_data.xml',
        'data/carbon_report.xml',
        'data/esg.esrs.csv',
        'data/esg.nace.csv',
        'data/res.country.state.csv',
        'data/uom_uom_data.xml',
        'data/esg_metric_survey_data.xml',
        'data/mail_template_data.xml',
        'data/esg_report_template_data.xml',
        'data/esg_csrd_knowledge_article_template_category_data.xml',
        'data/esg_csrd_knowledge_article_template_csrd_data.xml',
        'data/esg_csrd_knowledge_article_template_vsme_data.xml',
        'report/esg_carbon_emission_report_views.xml',
        'wizard/esg_metric_ask_feedback_views.xml',
        'wizard/factors_auto_assignment_wizard_views.xml',
        'views/account_move_views.xml',
        'views/esg_action_views.xml',
        'views/esg_assignation_line_views.xml',
        'views/esg_emission_factor_views.xml',
        'views/esg_emission_source_views.xml',
        'views/esg_esrs_views.xml',
        'views/esg_gas_views.xml',
        'views/esg_database_views.xml',
        'views/esg_other_emission_views.xml',
        'views/esg_metric_views.xml',
        'views/esg_report_views.xml',
        'views/knowledge_article_views.xml',
        'views/survey_user_input_views.xml',
        'views/res_config_settings_views.xml',
        'views/esg_menus.xml',
        'security/ir.access.csv',
    ],
    'demo': [
        'demo/demo_data.xml',
        'demo/esg_action_demo_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'esg/static/src/**/*',
            ('remove', 'esg/static/src/views/esg_carbon_emission_graph/**'),
            ('remove', 'esg/static/src/views/esg_carbon_emission_pivot/**'),
            ('remove', 'esg/static/src/scss/*.dark.scss'),
        ],
        'web.assets_web_dark': [
            'esg/static/src/scss/*.dark.scss',
        ],
        'web.assets_backend_lazy': [
            'esg/static/src/views/esg_carbon_emission_graph/**',
            'esg/static/src/views/esg_carbon_emission_pivot/**',
        ],
        'web.assets_unit_tests': [
            'esg/static/tests/esg_models.js',
        ],
    },
    'uninstall_hook': 'uninstall_hook',
    'application': True,
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
}
