# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Social Marketing',
    'category': 'Marketing/Social Marketing',
    'sequence': 175,
    'summary': 'Manage your social media and website visitors',
    'version': '1.3',
    'description': """Manage your social media and website visitors""",
    'website': 'https://www.odoo.com/app/social-marketing',
    'depends': ['web', 'mail', 'iap', 'link_tracker', 'digest', 'im_livechat'],
    'data': [
        'security/social_security.xml',
        'data/digest_data.xml',
        'data/ir_cron_data.xml',
        'data/social_tour.xml',
        'views/social_menu_views.xml',
        'views/digest_views.xml',
        'views/discuss_channel_views.xml',
        'views/social_account_views.xml',
        'views/social_live_post_views.xml',
        'views/social_media_views.xml',
        'views/social_post_image_views.xml',
        'views/social_post_template_views.xml',
        'views/social_post_views.xml',
        'views/social_stream_post_views.xml',
        'views/social_stream_views.xml',
        'views/im_livechat_channel_views.xml',
        'views/res_config_settings_views.xml',
        'views/utm_campaign_views.xml',
        'views/social_templates.xml',
        'security/ir.access.csv',
    ],
    'demo': [
        'data/social_demo.xml'
    ],
    'application': True,
    'assets': {
        'web.assets_backend': [
            'social/static/src/js/discuss/*',
            'social/static/src/js/fields/*',
            'social/static/src/js/add_stream_modal.js',
            'social/static/src/js/media_carousel_dialog.js',
            'social/static/src/js/post_kanban_view.js',
            'social/static/src/js/social_action_connect_account.js',
            'social/static/src/js/social_post_calendar_controller.js',
            'social/static/src/js/social_post_calendar_model.js',
            'social/static/src/js/social_post_calendar_common_renderer.js',
            'social/static/src/js/social_post_calendar_year_renderer.js',
            'social/static/src/js/social_post_calendar_renderer.js',
            'social/static/src/js/social_post_calendar_view.js',
            'social/static/src/js/social_post_formatter_mixin.js',
            'social/static/src/js/social_post_preview_field.js',
            'social/static/src/js/stream_post_comment.js',
            'social/static/src/js/stream_post_comment_list.js',
            'social/static/src/js/stream_post_comments.js',
            'social/static/src/js/stream_post_comments_reply.js',
            'social/static/src/js/stream_post_kanban_controller.js',
            'social/static/src/js/stream_post_kanban_dashboard.js',
            'social/static/src/js/stream_post_kanban_model.js',
            'social/static/src/js/stream_post_kanban_record.js',
            'social/static/src/js/stream_post_kanban_refresh_banner.js',
            'social/static/src/js/stream_post_kanban_renderer.js',
            'social/static/src/js/stream_post_kanban_view.js',
            'social/static/src/js/tours/social.js',
            'social/static/src/scss/discuss.scss',
            'social/static/src/scss/social.scss',
            'social/static/src/xml/**/*',
        ],
        # the social livechat is also rendered on the public discuss page
        'mail.assets_public': [
            'social/static/src/js/discuss/*',
            'social/static/src/scss/discuss.scss',
            'social/static/src/xml/discuss/*',
        ],
        'web.assets_web_dark': [
            'social/static/src/scss/social.dark.scss',
        ],
        'web.assets_unit_tests': [
            'social/static/src/tests/**/*',
        ]
    },
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
}
