# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import _, fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    l10n_at_pos_test_mode = fields.Boolean(related="company_id.l10n_at_pos_test_mode", string="Test Fiskaly",
            readonly=False, help="Enable this to use fiskaly services for testing purpose")
    l10n_at_fiskaly_organization_id = fields.Char(related="company_id.l10n_at_fiskaly_organization_id")
    l10n_at_fiskaly_api_key = fields.Char(related="company_id.l10n_at_fiskaly_api_key", string="Fiskaly API Key (AUT)", groups="base.group_system")
    l10n_at_fiskaly_api_secret = fields.Char(related="company_id.l10n_at_fiskaly_api_secret", string="Fiskaly API Secret (AUT)", groups="base.group_system")
    l10n_at_fiskaly_access_token = fields.Char(related="company_id.l10n_at_fiskaly_access_token", string="API Access Token", groups="base.group_system")
    l10n_at_fon_participant_id = fields.Char(related="company_id.l10n_at_fon_participant_id", string="Participation Identifier", readonly=False)
    l10n_at_fon_user_id = fields.Char(related="company_id.l10n_at_fon_user_id", string="User Identifier", readonly=False)
    l10n_at_fon_user_pin = fields.Char(related="company_id.l10n_at_fon_user_pin", string="User Pin", groups="base.group_system", readonly=False)
    l10n_at_cash_regid = fields.Char(related='pos_config_id.l10n_at_cash_regid', string="Fiskaly Cash Register ID", readonly=True, copy=False, help="Cash register identifier for this config generated by fiskaly")

    def action_l10n_at_authenticate_fon_credentials(self):
        self.company_id.action_l10n_at_authenticate_fon_credentials()
        return self._show_notification("success", _("FON Authenticated Successfully!"))

    def action_generate_fiskaly_credentials(self):
        self.company_id.action_generate_fiskaly_credentials()
        self.action_auth_fiskaly_credentials()
        return self._show_notification("success", _("Fiskaly Authentication Successful!"))

    def action_auth_fiskaly_credentials(self, refresh=False):
        self.company_id.auth_fiskaly_credentials(refresh=refresh)

    def _show_notification(self, notification_type, message=""):
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'type': notification_type,
                'message': message,
                'next': {'type': 'ir.actions.act_window_close'},
            }
        }
