# Part of Odoo. See LICENSE file for full copyright and licensing details.
from . import ai_skill
from . import call_transcription_mixin
from . import ai_tool
from . import ai_agent
from . import ai_agent_source
from . import ai_embedding
from . import ai_embedding_mixin
from . import ai_session
from . import ai_web_scraper_batch
from . import ai_web_page
from . import ir_attachment
from . import ir_model_fields
from . import mail_composer_mixin
from . import mail_message
from . import mail_render_mixin
from . import mail_template
from . import res_partner
from . import ai_prompt_button
from . import ai_composer
from . import discuss_channel
from . import discuss_channel_member
from . import discuss_call_history
from . import mail_thread
from . import models
from . import ir_actions_server
from . import ai_attachment_vacuum
from . import mail_call_artifact
