# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import common
from . import common_payment_report
from . import test_2_weeks_calendar
from . import test_domain_condition_rules
from . import test_headcount
from . import test_missing_employee_payrun
from . import test_multi_contract
from . import test_payment_report
from . import test_payroll_dependencies
from . import test_payroll_properties
from . import test_payroll_warning
from . import test_payroll_warning_stream
from . import test_payrun
from . import test_payrun_flow
from . import test_payslip_allocations
from . import test_payslip_computation
from . import test_payslip_empty_contract
from . import test_payslip_flow
from . import test_performance
from . import test_resource
from . import test_rule_category
from . import test_rule_parameter
from . import test_salary_attachment
from . import test_schedule_relative_payslip
from . import test_work_entry
from . import test_ytd
from . import test_payslip_email_settings
from . import test_timeoff_defer
from . import test_leave_state_change
from . import test_salary_rule
from . import test_payslip_access_rights
from . import test_salary_increase_wizard
from . import test_versions_validation
from . import test_payrun_search
from . import test_payslip_report
from . import test_salary_rule_explicit_fields_warning
from . import test_payslip_correction
from . import test_variable_schedule
from . import test_hr_employee
from . import test_payroll_config_settings
from . import test_payroll_worked_days_count
from . import test_time_rule_payslip
from . import test_time_type_data
