# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Payroll',
    'category': 'Human Resources/Payroll',
    'sequence': 290,
    'summary': 'Manage your employee payroll',
    'application': True,
    'uninstall_hook': "uninstall_hook",
    'post_init_hook': "_post_init_hook",
    'depends': [
        'mail',
        'html_editor',
        'hr_holidays_gantt',
    ],
    'data': [
        'security/hr_payroll_security.xml',
        'wizard/hr_payslip_correction_wizard_views.xml',
        'wizard/hr_payroll_salary_increase_wizard_views.xml',
        'wizard/hr_salary_attachment_generate_multi_wizard.xml',
        'wizard/hr_payroll_set_schedule_wizard_views.xml',
        'views/hr_contract_template_views.xml',
        'views/hr_payroll_structure_views.xml',
        'views/hr_payroll_structure_type_views.xml',
        'views/hr_salary_rule_category_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_salary_rule_section_views.xml',
        'views/hr_payslip_line_views.xml',
        'views/hr_payslip_worked_days_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/hr_version_views.xml',
        'views/hr_payslip_input_views.xml',
        'views/res_partner_bank_views.xml',
        'views/hr_salary_attachment_views.xml',
        'views/hr_employee_views.xml',
        'views/payroll_config_settings_views.xml',
        'views/hr_payroll_declaration_mixin_views.xml',
        'views/hr_payroll_employee_declaration_views.xml',
        'views/hr_leave_views.xml',
        'views/hr_payroll_warning_views.xml',
        'data/hr_payroll_sequence.xml',
        'data/report_paperformat_data.xml',
        'views/hr_payroll_report.xml',
        'data/decimal_precision_data.xml',
        'data/hr_payroll_structure_data.xml',
        'data/hr_payroll_structure_type_data.xml',
        'data/hr_salary_rule_category_data.xml',
        'data/hr_salary_rule_data.xml',
        'data/hr_work_entry_type_data.xml',
        'data/mail_activity_type_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/hr_payroll_tour.xml',
        'data/hr_contract_salary_benefits_data.xml',
        'views/res_config_settings_views.xml',
        'views/report_contributionregister_templates.xml',
        'views/report_payslip_templates.xml',
        'views/report_light_payslip_templates.xml',
        'views/hr_work_entry_type_views.xml',
        'views/hr_time_rule_views.xml',
        'views/hr_rule_parameter_views.xml',
        'views/hr_payroll_dashboard_views.xml',
        'views/hr_payroll_headcount_views.xml',
        'views/hr_contract_salary_benefit_views.xml',
        'views/mail_message_views.xml',
        'views/hr_payroll_menu.xml',
        'wizard/hr_payroll_payment_report_wizard.xml',
        'data/hr_payroll_warning_data.xml',
        'views/hr_employee_type_views.xml',
        'security/ir.access.csv',
        'data/mail_message_subtype_data.xml',
        'views/resource_calendar_attendance_views.xml',
        'views/resource_calendar_leave_views.xml',
    ],
    'demo': [
        'data/hr_payroll_structure_demo.xml',
        'data/hr_payroll_structure_type_demo.xml',
        'data/hr_payroll_demo.xml',
        'data/hr_salary_rule_demo.xml'
        ],
    'assets': {
        "im_livechat.assets_embed_core": [
            "hr_payroll/static/src/core/common/**/*",
        ],
        "mail.assets_public": [
            "hr_payroll/static/src/core/common/**/*",
        ],
        "portal.assets_chatter_helpers": [
            "hr_payroll/static/src/core/common/**/*",
        ],
        'web.assets_backend': [
            'hr_payroll/static/src/**/*',
            ('remove', 'hr_payroll/static/src/views/lazy/**'),
        ],
        'web.assets_backend_lazy': [
            'hr_payroll/static/src/views/lazy/**',
        ],
        'web.assets_unit_tests': [
            'hr_payroll/static/tests/**/*',
            ('remove', 'hr_payroll/static/tests/tours/**/*'),
        ],
        'web.assets_tests': [
            'hr_payroll/static/tests/tours/**/*'
        ],
    },
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
}
