from . import account_analytic_line
from . import hr_employee
from . import planning_slot
from . import product_product
from . import product_template
from . import res_company
from . import res_config_settings
from . import sale_order
from . import sale_order_line
