from . import utils
from . import ir_ui_menu
from . import res_company
from . import res_config_settings
from . import hr_employee
from . import zkteco_terminal
from . import zkteco_transactions
from . import hr_attendance
from . import hr_work_location
