from . import test_voip_access_rights
from . import test_voip_activity_mixin
from . import test_voip_call
from . import test_voip_call_activity_access
from . import test_voip_call_flow
from . import test_voip_call_flow_time_condition
from . import test_voip_mail_call_artifact
from . import test_voip_controller
from . import test_voip_im_status
from . import test_voip_ivr
from . import test_voip_mail_activity
from . import test_voip_multiple_providers
from . import test_voip_music_on_hold
from . import test_pbx_service
from . import test_pbx_tenant_recovery
from . import test_voip_pbx_routing
from . import test_voip_queue_agent
from . import test_voip_requirement
from . import test_voip_res_partner
from . import test_voip_session_info
from . import test_voip_t9
from . import test_voip_time_condition
from . import test_voip_tours
from . import test_voip_user_config
from . import common_voip
from . import test_phone_service_signature
from . import test_phone_service_credentials
from . import test_phone_service_endpoint_validation
from . import test_phone_service_access
from . import test_phone_service_errors
from . import test_phone_number_utils
from . import test_phone_service_event
from . import test_buy_number_wizard
from . import test_phone_service_notifications
from . import test_voip_did_number
from . import test_voip_sound
from . import test_voip_extension
from . import test_voip_extension_destination_mixin
from . import test_voip_voicemail
from . import test_voip_voicemail_message
from . import test_wav
from . import test_linphone_provisioning
