# Part of Odoo. See LICENSE file for full copyright and licensing details.
from . import common
from . import test_ai_access
from . import test_ai_agent
from . import test_ai_agent_compute_date
from . import test_ai_agent_source
from . import test_ai_embedding
from . import test_ai_message_parts
from . import test_ai_methods
from . import test_ai_open_menu_graph_tour
from . import test_ai_session
from . import test_ai_url_scraper_controller
from . import test_ai_web_page
from . import test_ai_web_scraper_batch
from . import test_mail_call_artifact_ai
from . import test_data
from . import test_discuss_channel
from . import test_instance_validation
from . import test_ir_actions_server
from . import test_ir_attachment
from . import test_llm_tool_calling
from . import test_schema_validation
from . import test_tool_update_records
from . import test_ai_prompt_button
from . import test_ai_image_tools
from . import test_ai_composer
from . import test_tool_create_records
from . import test_markdown_formatting
