import re

from odoo import api, fields, models
from odoo.exceptions import ValidationError
from odoo.fields import Domain


class AwRule(models.Model):
    _name = "aw.rule"
    _description = "ActivityWatch Browser URL Rule"
    _order = "sequence"

    name = fields.Char(
        string="Name",
        required=True,
        help="Give your rule a clear name so you can easily recognize it later.\n\n"
             "Example: Customer Meeting."
    )
    active = fields.Boolean(default=True)
    company_id = fields.Many2one('res.company', string='Company')
    regex = fields.Char(
        string="Regex",
        required=True,
        help="This tells Odoo which activity to track from ActivityWatch. Each activity that matches this pattern will create a new event, and all following related actions are counted as part of it until a different activity starts. Only activities longer than 1 minute are tracked.\n\n"
             "Example pattern: Meet - (.*)\\|https://meet.google.com captures each Google Meet meeting.\n\n"
             "Tip: The parts in parentheses (…) are captured automatically and can be used in the Template or in the Description.\n\n"
             "Example of a new event:\n"
             "Open Customer A Meeting → a new event is created\n"
             "Search for info about Customer A → counted as part of the same event\n"
             "Open Customer B Meeting → a new event starts."
    )
    type = fields.Selection(
        [
            ("email", "Email"),
            ("call", "Call"),
            ("messaging", "Messaging"),
            ("meeting", "Meeting"),
            ("document", "Document"),
            ("spreadsheet", "Spreadsheet"),
            ("presentation", "Presentation"),
            ("development", "Development"),
            ("odoo", "Odoo"),
            ("planning", "Planning"),
            ("other", "Other"),
        ],
        string="Type",
        required=True,
        help="Choose the icon that will appear next to activities matched by this rule in the Timesheet Assistant list.\n\n"
             "Example: Call for a Google Meet meeting."
    )
    template = fields.Char(
        string="Template",
        required=True,
        help="Set the name that Odoo will use to recognize similar activities for automatic suggestions.\n\n"
             "You can include dynamic parts from your regex using ($1), ($2), etc. These come from the parentheses in your regex.\n\n"
             "Example: Template Customer Meeting ($1) → if the meeting ID is abc-123, the event will be named Customer Meeting (abc-123) and used to identify similar meetings for suggestions."
    )
    description = fields.Char(
        string="Description",
        help="Optional extra information for the Timesheet Assistant list. "
            "You can use ($1), ($2), etc. from your regex to include dynamic details. "
            "Example: 'Customer Meeting ($1) - Topic: $2' will appear as "
            "'Customer Meeting (abc-123) - Topic: Project Kickoff'."
    )
    project_id = fields.Many2one(
        "project.project",
        string="Project",
        domain="[('allow_timesheets', '=', True), ('company_id', 'in', [company_id, False])]",
        compute="_compute_project_id",
        inverse="_inverse_project_id",
        store=True,
        readonly=False,
        help="Set a default project for activities matched by this rule. If you leave it blank, the system will suggest a project based on your previous choices for similar activities.\n\n"
             "Example: For recurring customer meetings, leave blank if each meeting could relate to a different project."
    )
    task_id = fields.Many2one(
        "project.task",
        domain="[('project_id', '!=', False), ('project_id', '=?', project_id), ('company_id', 'in', [company_id, False])]",
        string="Task",
        index="btree_not_null",
        help="Set a default task for activities matched by this rule. If you leave it blank, the system will suggest a task based on your previous choices for similar activities.\n\n"
             "Example: For recurring customer meetings, leave blank if each meeting could relate to a different task."
    )
    always_active = fields.Boolean(
        string="Always Active",
        default=False,
        help="Enable this to track activities even if you’re not moving the mouse or typing. This is useful for meetings, webinars, or any activity where you’re watching or listening without interacting.\n\n"
             "Example: A Google Meet meeting will still be tracked even if you’re idle for a few minutes."
    )
    side_activity = fields.Boolean(
        compute="_compute_side_activity",
        store=True,
        readonly=False,
        help="When enabled, suggestions generated by this rule will not change the active project or task for your subsequent activities, allowing you to handle quick interruptions (like checking messages or notifications) without affecting your ongoing timeline tracking."
    )
    threshold = fields.Float(
        default=1,
        help="Minimum duration required for an activity to appear in suggestions",
    )
    sequence = fields.Integer(default=10)
    match_count = fields.Integer(compute="_compute_match_count", default=0, export_string_translation=False)
    applies_to = fields.Selection(
        [
            ("everyone", "Everyone"),
            ("departments", "Departments"),
            ("private", "Private"),
        ],
        default=lambda self: (
            "everyone"
            if self.env.user.has_group("hr_timesheet.group_timesheet_manager")
            else "private"
        ),
        string="Applies To",
        required=True,
    )
    department_ids = fields.Many2many("hr.department", string="Departments", domain="['|', ('company_id', '=', False), ('company_id', '=?', company_id)]")
    is_editable = fields.Boolean(compute="_compute_is_editable", export_string_translation=False)
    is_my_department_rule = fields.Boolean(search="_search_is_my_department_rule", store=False)

    @api.model
    def _search_is_my_department_rule(self, operator, value):
        department = self.env.user.employee_id.department_id
        if not department:
            return Domain.FALSE

        return [
            ('applies_to', '=', 'departments'),
            ('department_ids', 'parent_of', department.id),
        ]

    @api.model
    def get_applicable_rules(self, fields):
        employee = self.env.user.employee_id
        if not employee:
            return []
        domain = [
            ('template', '!=', False),
            '|',
                ('applies_to', '=', 'everyone'),

                '|',
                    '&',
                        ('applies_to', '=', 'departments'),
                        ('department_ids', 'parent_of', employee.department_id.id),

                    '&',
                        ('applies_to', '=', 'private'),
                        ('create_uid', '=', self.env.user.id),
        ]
        return self.search_read(domain, fields)

    @api.depends("type")
    def _compute_side_activity(self):
        for rule in self:
            rule.side_activity = rule.type == "messaging"

    @api.depends_context("uid")
    @api.depends("applies_to", "create_uid")
    def _compute_is_editable(self):
        is_manager = self.env.user.has_group("hr_timesheet.group_timesheet_manager")
        for rule in self:
            if not rule._origin:
                rule.is_editable = True
                continue
            rule.is_editable = is_manager or (
                rule.applies_to == "private" and rule.create_uid == self.env.user
            )

    @api.depends("task_id.project_id", "company_id")
    def _compute_project_id(self):
        for rule in self:
            if rule.project_id and rule.project_id.company_id and rule.project_id.company_id != rule.company_id:
                rule.project_id = False
            elif rule.task_id:
                rule.project_id = rule.task_id.project_id

    def _inverse_project_id(self):
        for rule in self:
            if rule.task_id and rule.task_id.project_id != rule.project_id:
                rule.task_id = False

    @api.onchange("project_id")
    def _onchange_project_id(self):
        self._inverse_project_id()

    @api.onchange("company_id")
    def _onchange_company_id(self):
        self._remove_records_from_other_companies()

    def _remove_records_from_other_companies(self):
        """Unlink the project, task and departments that no longer belong to the company of their rule."""
        # sudo: the cleanup can be triggered by a user who cannot write on the rule
        for rule in self.sudo().filtered("company_id"):
            if rule.project_id.company_id and rule.project_id.company_id != rule.company_id:
                rule.project_id = False
            if rule.task_id.company_id and rule.task_id.company_id != rule.company_id:
                rule.task_id = False
            if rule.applies_to == "departments":
                rule.department_ids = rule.department_ids.filtered(
                    lambda d: not d.company_id or d.company_id == rule.company_id
                )

    def _to_python_regex(self, regex):
        """Convert JS named group syntax (?<name>...) to Python syntax (?P<name>...)."""
        return re.sub(r'\(\?<(\w+)>', r'(?P<\1>', regex)

    @api.depends("regex")
    def _compute_match_count(self):
        for record in self:
            if not record.regex:
                continue

            try:
                pattern = re.compile(self._to_python_regex(record.regex))
                record.match_count = pattern.groups
            except re.error:
                record.match_count = 0

    @api.constrains("regex")
    def _check_regex(self):
        for record in self:
            try:
                re.compile(self._to_python_regex(record.regex))
            except re.error:
                raise ValidationError(self.env._("Invalid regex: %(regex)s", regex=record.regex))

    def write(self, vals):
        if vals.get("applies_to") == "private" and self.filtered(lambda r: r.create_uid.id != self.env.uid):
            raise ValidationError(
                self.env._("You can’t make a rule created by another user private.")
            )

        result = super().write(vals)
        if "company_id" in vals:
            self._remove_records_from_other_companies()
        return result
