# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo.exceptions import UserError

from odoo import _, api, fields, models

L10N_PH_CERTIFICATE_TAG_FORM = {
    '1601/1604A': '2307',
    '1601/1604B': '2307',
    '1601/1604FA': '2306',
    '1601/1604FB': '2306',
}


class AccountMove(models.Model):
    _inherit = 'account.move'

    def _l10n_ph_certificate_forms(self):
        """Return the set of BIR forms ({'2306', '2307'}) this bill can issue, based on the
        withholding tax tags applied on its lines."""
        self.ensure_one()
        certificate_moves = self | self.reconciled_payment_ids.move_id
        return {
            L10N_PH_CERTIFICATE_TAG_FORM[tag.name]
            for tag in certificate_moves.line_ids.tax_tag_ids
            if tag.name in L10N_PH_CERTIFICATE_TAG_FORM
        }

    l10n_ph_is_certificate_exportable = fields.Boolean(compute='_compute_l10n_ph_is_certificate_exportable')

    @api.depends('state', 'move_type', 'country_code', 'line_ids.tax_tag_ids', 'reconciled_payment_ids')
    def _compute_l10n_ph_is_certificate_exportable(self):
        """Whether a BIR 2306/2307 withholding tax certificate can be issued for this bill."""
        for move in self:
            move.l10n_ph_is_certificate_exportable = (
                move.state == 'posted'
                and move.move_type == 'in_invoice'
                and move.country_code == 'PH'
                and bool(move._l10n_ph_certificate_forms())
            )

    @api.depends('l10n_ph_is_certificate_exportable')
    def _compute_display_send_button(self):
        # EXTENDS 'account'
        super()._compute_display_send_button()
        for move in self:
            if move.l10n_ph_is_certificate_exportable:
                move.display_send_button = True

    def _get_mail_template(self):
        # EXTENDS 'account': an eligible vendor bill is sent with its withholding certificate.
        if self and all(move.l10n_ph_is_certificate_exportable for move in self):
            return self.env.ref('l10n_ph_reports.mail_template_bir_certificate')
        return super()._get_mail_template()

    def _l10n_ph_get_certificate_filename(self):
        self.ensure_one()
        return self.env['l10n_ph.2306_2307.report.handler']._l10n_ph_certificate_filename(
            self.commercial_partner_id.name,
            sorted(self._l10n_ph_certificate_forms()),
            {'l10n_ph_certificate_move_id': self.id},
        )

    def _get_invoice_report_filename(self, extension='pdf', report=None):
        # EXTENDS 'account': set the filename as the BIR WHT certificate filename
        if self.l10n_ph_is_certificate_exportable:
            return f'{self._l10n_ph_get_certificate_filename()[:-4]}.{extension}'
        return super()._get_invoice_report_filename(extension=extension, report=report)

    def action_l10n_ph_print_bir_certificates(self):
        """Return the PDF generated by the BIR 2306/2307 report filtered to this move."""
        bills = self.filtered('l10n_ph_is_certificate_exportable')
        if not bills:
            raise UserError(_("None of the selected documents have BIR 2306/2307 withholding tax lines to certify."))

        main_report = self.env.ref('l10n_ph_reports.2306_2307_report')
        options = main_report.get_options(previous_options={})
        options['l10n_ph_certificate_move_ids'] = bills.ids
        return self.env['l10n_ph.2306_2307.report.handler']._action_export_bir_certificates(options)

    def action_l10n_ph_send_certificates(self):
        """Email the BIR certificate(s) to the vendor(s) through the standard Send wizard."""
        bills = self.filtered('l10n_ph_is_certificate_exportable')
        if not bills:
            raise UserError(_("None of the selected documents have BIR 2306/2307 withholding tax lines to certify."))
        return bills.action_send_and_print()
