# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import fields, models


class WebsiteVisitorPushSubscription(models.Model):
    """ This model stores all the necessary information for sending push
    notifications to a website visitor. A new record of this model is created
    whenever a visitor consents to receiving push notifications.

    A visitor can have multiple push subscriptions if they use several devices / browsers.
    (push_subscriptions are 'merged' onto the main visitor, see website.visitor#_merge_visitor for
    more information.) """

    _name = 'website.visitor.push.subscription'
    _description = 'Push Subscription for a Website Visitor'
    _log_access = False
    _rec_name = 'website_visitor_id'

    endpoint = fields.Char(string='Browser endpoint', required=True)
    keys = fields.Char(string='Browser keys', required=True,
                       help=("It refer to browser keys used by the notification: \n"
                             "- p256dh: It's the subscription public key generated by the browser. The browser will \n"
                             "          keep the private key secret and use it for decrypting the payload\n"
                             "- auth: The auth value should be treated as a secret and not shared outside of Odoo"))
    website_visitor_id = fields.Many2one('website.visitor', string="Website Visitor",
        required=True, readonly=True, index=True, ondelete='cascade')

    _unique_endpoint = models.Constraint(
        'unique(endpoint)',
        'An endpoint cannot be assigned multiple times.')
