from . import ir_actions_report
from . import ir_ui_menu
from . import mail_template
from . import planning_slot
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import resource_resource
