{
    'name': 'Field Service',
    'summary': 'Plan intervention in planning',
    'category': 'Human Resources/Planning',
    'author': 'Odoo S.A.',
    'website': 'https://www.odoo.com/app/planning',
    'license': 'OEEL-1',
    'depends': [
        'planning',
        'web_map',
        'base_geolocalize',
        'portal_rating',
    ],
    'data': [
        'security/planning_field_service_security.xml',
        'report/planning_analysis_report_views.xml',
        'report/report_planning_field_service_intervention_reports.xml',
        'report/report_planning_field_service_intervention_templates.xml',
        'data/planning_field_service_cron.xml',
        'data/mail_template_data.xml',
        'data/mail_message_subtype_data.xml',
        'data/planning_field_service_tour.xml',
        'data/portal_entry_data.xml',
        'views/planning_slot_views.xml',
        'views/planning_slot_portal_templates.xml',
        'views/planning_templates.xml',
        'views/rating_rating_views.xml',
        'views/mail_activity_plan_views.xml',
        'views/mail_activity_type_views.xml',
        'views/res_config_settings_views.xml',
        'views/planning_field_service_menus.xml',
        'security/ir.access.csv',
    ],
    'demo': [
        'data/planning_field_service_demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'planning_field_service/static/src/**/*',
            ('remove', 'planning_field_service/static/src/views/planning_gantt/**'),
            ('remove', 'planning_field_service/static/src/views/planning_field_service_map/**'),
            ('remove', 'planning_field_service/static/src/views/planning_field_service_live_map/**'),
            ('remove', 'planning_field_service/static/src/views/planning_field_service_map_timeline/**'),
        ],
        'web.assets_frontend': [
            'planning_field_service/static/src/js/tours/planning_field_service_tour.js',
        ],
        'web.assets_backend_lazy': [
            'planning_field_service/static/src/views/planning_gantt/**',
            'planning_field_service/static/src/views/planning_field_service_map/**',
            'planning_field_service/static/src/views/planning_field_service_live_map/**',
            'planning_field_service/static/src/views/planning_field_service_map_timeline/**',
        ],
        'web.assets_unit_tests': [
            'planning_field_service/static/tests/**/*',
            ('remove', 'planning_field_service/static/tests/tours/*'),
        ],
        'web.assets_tests': [
            'planning_field_service/static/tests/tours/*.js',
        ],
    },
    'application': True,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
