<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
	<xs:element name="IR56E">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Section">  <!-- Section -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="3" />
							<xs:pattern value="[0-9a-zA-Z]*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ERN">  <!-- ERN -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
							<xs:maxLength value="8" />
							<xs:pattern value="[0-9]*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SubDate">  <!-- Submission Date -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="8" />
							<xs:pattern value="[0-9]*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ErName">  <!-- Employer’s Name -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
							<xs:maxLength value="70" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="NAME_OF_SIGNER">  <!-- Name of Signer -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
							<xs:maxLength value="27" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Designation">  <!-- Designation -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
							<xs:maxLength value="25" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="NoRecordBatch">  <!-- No. of Records in Batch -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="5" />
							<xs:pattern value="[0-9]*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="TotIncomeBatch">  <!-- Total Income in Batch -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
							<xs:maxLength value="13" />
							<xs:pattern value="[0-9]*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IR56VER">  <!-- Version Number -->
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="5" />
							<xs:enumeration value="E0001" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">  <!-- Employee’s IR56E record -->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SheetNo">  <!-- Sheet No. -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="6" />
										<xs:pattern value="[0-9]*[1-9]{1,}[0-9]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="HKID" default="AA000000A">  <!-- Employee’s HKID with Check Digit -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="9" />
										<xs:pattern value="[A-Z a-z]{0,1}[A-Za-z]{1}[0-9]{6}[Aa0-9]{0,1}" />
										<xs:pattern value="[A-Za-z]{1}[0-9]{6}[Aa0-9]{0,1}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TypeOfForm">  <!-- Status -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="1" />
										<xs:enumeration value="A" />
										<xs:enumeration value="O" />
										<xs:enumeration value="R" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Surname">  <!-- Employee’s Surname -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
										<xs:maxLength value="20" />
										<xs:pattern value="[A-Z a-z'\.\-]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="GivenName">  <!-- Employee’s Given Names in Full -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
										<xs:maxLength value="55" />
										<xs:pattern value="[A-Z a-z0-9!#$%&amp;\*\(\)_\+\-=\\:&quot;;&apos;&lt;&gt;?,\./@]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NameInChinese">  <!-- Employee’s Full Name in Chinese -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="25" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Sex">  <!-- Employee’s Sex -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="M" />
										<xs:enumeration value="F" />
										<xs:enumeration value="m" />
										<xs:enumeration value="f" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="MaritalStatus">  <!-- Employee’s Marital Status -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="1" />
										<xs:enumeration value="2" />
										<xs:enumeration value="" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PpNum">  <!-- Employee’s Passport No. and Place of Issue -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="40" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SpouseName">  <!-- Spouse’s Name -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SpouseHKID">  <!-- Spouse’s HKID with Check Digit -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="9" />
										<xs:pattern value="[A-Z a-z]{0,1}[A-Za-z]{1}[0-9]{6}[Aa0-9]{0,1}" />
										<xs:pattern value="[A-Za-z]{1}[0-9]{6}[Aa0-9]{0,1}" />
										<xs:pattern value="[ ]{0,1}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SpousePpNum">  <!-- Spouse’s Passport No. and Place of Issue -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="40" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RES_ADDR_LINE1">  <!-- Employee’s Residential Address Line 1 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RES_ADDR_LINE2">  <!-- Employee’s Residential Address Line 2 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RES_ADDR_LINE3">  <!-- Employee’s Residential Address Line 3 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AreaCodeResAddr">  <!-- Area Code of Employee’s Residential Address -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="1" />
										<xs:enumeration value="H" />
										<xs:enumeration value="K" />
										<xs:enumeration value="N" />
										<xs:enumeration value="F" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="POS_ADDR_LINE1">  <!-- Employee’s Postal Address Line 1 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="POS_ADDR_LINE2">  <!-- Employee’s Postal Address Line 2 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="POS_ADDR_LINE3">  <!-- Employee’s Postal Address Line 3 -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="POS_ADDR_AREA">  <!-- Area Code of Employee's Postal Address -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="1" />
										<xs:enumeration value="H" />
										<xs:enumeration value="K" />
										<xs:enumeration value="N" />
										<xs:enumeration value="F" />
										<xs:enumeration value="" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Capacity">  <!-- Capacity in which Employed -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="40" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RTN_ASS_YR">  <!-- Year of the Reported Employement Period -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="4" />
										<xs:pattern value="[0-9]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="COMMENCE_DATE">  <!-- Date of Commencement of Employment -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="8" />
										<xs:pattern value="[0-9]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="MR_FIXED_INCOME" type="mandatory_amount" />  <!-- Monthly Rate of Fixed Income -->
							<xs:element name="MR_ALLOWANCE" type="amount" />  <!-- Monthly Rate of Allowances -->
							<xs:element name="FLU_INCOME" type="amount" />  <!-- Fluctuating Income -->
							<xs:element name="PlaceOfResInd">  <!-- Place of Residence Indicator -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="1" />
										<xs:enumeration value="0" />
										<xs:enumeration value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AddrOfPlace1">  <!-- Address of Place of Residence -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="90" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NatureOfPlace1">  <!-- Nature of Place of Residence -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="19" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="RentPaidEr1" type="rentAmt" />  <!-- Monthly Rent Paid to Landlord by Employer -->
							<xs:element name="RentPaidEe1" type="rentAmt" />  <!-- Monthly Rent Paid to Landlord by Employee -->
							<xs:element name="RentRefund1" type="rentAmt" />  <!-- Monthly Rent Refunded to Employee by Employer -->
							<xs:element name="RentPaidErByEe1" type="rentAmt" />  <!-- Monthly Rent Paid to Employer by Employee -->		
							<xs:element name="OverseaIncInd">  <!-- Non-Hong Kong Income Indicator -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="1" />
										<xs:enumeration value="0" />
										<xs:enumeration value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>	
							<xs:element name="NameOfOverseaCo">  <!-- Name of Non-Hong Kong Company -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="60" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AddrOfOverseaCo">  <!-- Address of Non-Hong Kong Company -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="60" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CON_SO_BEFORE_COMM">  <!-- Conditionally granted of Share Option before commencement of employment -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="1" />
										<xs:enumeration value="0" />
										<xs:enumeration value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>					
							<xs:element name="NUM_SHARE_GRANT" type="amount" />  <!-- Number of Shares granted covered by the option -->
							<xs:element name="SHARE_TYPE_COVER">  <!-- Type of shares covered by the option -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="20" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CON_PAID_GRANT_OF_OPTION">  <!-- Consideration paid for each share on the grant of the option -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="15" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CON_REQ_EXE_OPTION">  <!-- Consideration required for each share to exercise the option -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="15" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="OPTION_EXE_PER_FROM">  <!-- Period the option must be exercised: From -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="8" />
										<xs:pattern value="[0-9]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="OPTION_EXE_PER_TO">  <!-- Period the option must be exercised: To -->
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="8" />
										<xs:pattern value="[0-9]*" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="amount">
		<xs:restriction base="xs:string">
			<xs:maxLength value="9" />
			<xs:pattern value="[0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="rentAmt">
		<xs:restriction base="xs:string">
			<xs:maxLength value="7" />
			<xs:pattern value="[0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="mandatory_amount">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="9" />
			<xs:pattern value="[0-9]*" />
		</xs:restriction>
	</xs:simpleType>	
</xs:schema>
