{  # noqa: B018
    "name": "Phone",
    "summary": """Make and receive phone calls from within Odoo.""",
    "description": """Adds a softphone and helpers to make phone calls directly from within your Odoo database.""",
    "category": "Productivity/Phone",
    "sequence": 280,
    "version": "2.0",
    "depends": ["base", "bus", "iap", "mail", "phone_validation", "resource", "web", "web_mobile"],
    "data": [
        "security/voip_security.xml",
        "data/voip_data.xml",
        "data/mail_message_subtype_data.xml",
        "data/voip_voicemail_mail_template.xml",
        "data/voip_phone_number_request_mail_template.xml",
        "data/voip_template.xml",
        "data/iap_service_data.xml",
        "data/voip_cron.xml",
        "views/voip_provider_views.xml",
        "views/voip_call_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/res_users_settings_views.xml",
        "views/res_config_settings_views.xml",
        "views/voip_requirement_views.xml",
        "views/voip_requirement_group_views.xml",
        "wizards/voip_did_number_search_wizard_views.xml",
        "wizards/voip_did_number_request_wizard_views.xml",
        "data/ir_actions_todo_data.xml",
        "views/voip_did_number_views.xml",
        "views/voip_did_number_request_views.xml",
        "views/voip_sound_views.xml",
        "views/voip_music_on_hold_views.xml",
        "views/voip_voicemail_views.xml",
        "views/voip_menu_views.xml",
        "views/voip_extension_views.xml",
        "views/voip_call_flow_views.xml",
        "views/voip_time_condition_views.xml",
        "views/voip_call_group_views.xml",
        "views/voip_queue_views.xml",
        "views/voip_ivr_views.xml",
        "wizards/mail_activity_schedule_views.xml",
        'security/ir.access.csv',
    ],
    "demo": [
        "demo/res_groups.xml",
        "demo/voip_call.xml",
    ],
    "application": True,
    "author": "Odoo S.A.",
    "license": "OEEL-1",
    "assets": {
        "web.assets_backend": [
            "voip/static/src/**/*",
            ("remove", "voip/static/src/**/*.dark.scss"),
            ("remove", "voip/static/src/worker/**/*"),
            ("remove", "voip/static/src/service_worker.js"),
        ],
        "im_livechat.assets_embed_core": [
            "voip/static/src/core/common/**/*",
        ],
        "mail.assets_public": [
            'voip/static/src/core/common/**/*',
        ],
        "portal.assets_chatter_helpers": [
            "voip/static/src/core/common/**/*",
        ],
        "voip.assets_sip_prod": [
            "voip/static/lib/sip.js",
        ],
        "voip.assets_sip_demo": [
            "voip/static/lib/_mock/sip.js",
            "voip/static/src/core/web/session_demo_patch.js",
        ],
        "voip.assets_sip_tests": [
            ("include", "voip.assets_sip_demo"),
            "voip/static/tests/lib/_mock/sip.js",
        ],
        "web.assets_web_dark": [
            "voip/static/src/**/*.dark.scss",
        ],
        "web.assets_unit_tests": [
            "voip/static/tests/**/*",
            ("remove", "voip/static/tests/lib/**/*"),
            ("remove", "voip/static/tests/tours/**/*"),
            "voip/static/src/worker/*",
            # let the test environment init the worker with its own mocks
            ("remove", "voip/static/src/worker/init.js"),
        ],
        "web.assets_tests": [
            "voip/static/tests/tours/**/*",
        ],
        "bus.websocket_worker_assets": [
            "voip/static/src/worker/*",
        ],
    },
}
