from . import project_project
from . import planning_slot
from . import product_product
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import planning_vehicle_warehouse
from . import res_users
from . import stock_warehouse
